# Generated by Django 4.2.13 on 2024-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_localtion_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="users/default_profile_pict.jpeg", upload_to="users/"
            ),
        ),
    ]
